baseURL = "https://felixmihifavit.com"
disqusShortname = ""
enableGitInfo = true
    enableRobotsTXT = true
googleAnalytics = "G-0GZRVRLSQV"
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-texify2"
title = "Felix mihi favit"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe= true
[markup.highlight]
style = "tango"
[markup.tableOfContents]
  endLevel = 6
  ordered = false
  startLevel = 2

[author]
email = "felixlosada@outlook.com"
name = "Felix L"

[params]
numberedSubtitles = true
toc = true

[params.commentEngine]
code = """
"""

[params.buymeacoffee]
code = """
"""
